# Generated by Django 5.1.4 on 2025-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductCode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ProductID',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
