# Generated by Django 5.1.4 on 2025-01-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_productcode_alter_products_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubvariant',
            name='Stock',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
    ]
