# Generated by Django 5.1.4 on 2025-01-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsubvariant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubvariant',
            name='Stock',
        ),
    ]
