# Generated by Django 5.1.4 on 2025-01-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productsubvariant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvariant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='subvariant',
            unique_together={('variant', 'name')},
        ),
    ]
